package pers.hw.evtrack;


public enum Command {
    init,
    exit,
    reset,
    notice,
    message,
    image,
    locate,
    set_target,
    start_track,
    stop_track,
    enable_motion_autoctl,
    disable_motion_autoctl,
    start_motor,
    stop_motor,
    set_motor_val,
    get_motor_val,
    set_motion_ctl_pid,
    enable_field_autoctl,
    disable_field_autoctl,
    set_servo_val,
    get_servo_val,
    set_field_ctl_pid,
    get_client_cnt,
    send_to_all_clients,
    send_to_client,
    enable_multi_scale,
    disable_multi_scale,
    system_cmd,
    restart_server,
    halt,
    reboot,
    update_client_cnt,
    logout,
    update_pid
}
