#ifndef EVT_COMMAND_H
#define EVT_COMMAND_H

namespace evt
{

enum class Command
{
    INIT,
    RESET,
    NOTICE,
    MESSAGE,
    IMAGE,
    LOCATE,
    SET_TARGET,
    START_TRACK,
    STOP_TRACK,
    ENABLE_MOTION_AUTOCTL,
    DISABLE_MOTION_AUTOCTL,
    START_MOTOR,
    STOP_MOTOR,
    SET_MOTOR_VAL,
    GET_MOTOR_VAL,
    SET_MOTION_CTL_PID,
    ENABLE_FIELD_AUTOCTL,
    DISABLE_FIELD_AUTOCTL,
    SET_SERVO_VAL,
    GET_SERVO_VAL,
    SET_FIELD_CTL_PID,
    GET_CLIENT_CNT,
    SEND_TO_ALL_CLIENTS,
    SEND_TO_CLIENT,
    ENABLE_MULTI_SCALE,
    DISABLE_MULTI_SCALE,
    SYSTEM_CMD,
    RESTART_SERVER,
    HALT,
    REBOOT,
    UPDATE_CLIENT_CNT,
    LOGOUT,
    UPDATE_PID,
    LOGIN,
    ENUM_COUNT
};


} // namespace evt

#endif // EVT_COMMAND_H
